### ISSUE TITLE
Customize or remove "Join us on GitHub" link

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [SwissDataScienceCenter/renku-sphinx-theme#8]
I just created a documentation for a Python module using Renku (https://openturns.github.io/otfmi/master/)
The header "Join us on Github" refers to SwissDataScienceCenter, which is interesting yet confusing for my readers about the doc developers and the Python module.
For what I see, there is no way to either:
- remove this mention,
- or change the link to my Python module GitHub repo.

Is it possible to change this ?
Thanks in advance!

**Comment by bonii** [comment]
I would like to bump up the severity of this issue since it affects the usability of this theme. The README says it is customisable using `'github_repo' `but that generates an error as an unrecognized option. It would be great if this was easily customisable instead of [hacking it in layout.html as in the repo](https://github.com/SwissDataScienceCenter/renku-sphinx-theme/blob/master/renku_sphinx_theme/layout.html)

**Comment by rokroskar** [comment]
Hi @Claire-Eleutheriane and @bonii - apologies that this issue went unnoticed for this long! Should be a relatively simple fix I hope - we would happily accept a PR to fix this as well of course, if you'd like to give it a go!
